import Head from 'next/head';

type headType = {
  title: string;
  hrefIcon: string;
};

const HeadComponent = ({ title, hrefIcon }: headType) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={hrefIcon} />
      </Head>
    </div>
  );
};

export default HeadComponent;
